version: 2.1
jobs:
  build_deb_pkg:
    docker:
      - image: cimg/base:stable
    environment:
      PKG_NAME: "janus"
      PKG_VERSION: "1.0.0"
      PKG_BUILD_NUMBER: "1"
      PKG_ARCH: "armhf"
      PKG_ID: "${PKG_NAME}_${PKG_VERSION}-${PKG_BUILD_NUMBER}_${PKG_ARCH}"
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.11
      - run:
          name: Enable multiarch builds with QEMU
          command: |
            docker run \
              --rm \
              --privileged \
              multiarch/qemu-user-static \
              --reset \
              -p yes
      - run:
          name: Create multiarch build context
          command: docker context create builder
      - run:
          name: Create multiplatform builder
          command: |
            docker buildx create builder \
              --name builder \
              --driver docker-container \
              --use
      - run:
          name: Ensure builder has booted
          command: docker buildx inspect --bootstrap
      - run:
          name: Build docker image with .deb package
          command: |
            docker buildx build \
              --platform linux/arm/v7 \
              --build-arg PKG_VERSION \
              --target=artifact \
              --output type=local,dest=$(pwd)/releases/ \
              .
      - store_artifacts:
          path: releases/${PKG_ID}.deb
workflows:
  build:
    jobs:
      - build_deb_pkg
